### ISSUE TITLE
2 files are missing

### ISSUE THREAD

**Issue by adem0x** [Sovos-Compliance/direct-bpl-loader#3]
These 2 files are missing:

Tests\HijackGetProcTest.pas
Tests\HijackLoadLibraryTest.pas

Could you add them to the repo please

**Comment by jsbattig** [comment]
The repo is not complete yet.
I'm working with a contractor that has been writing this for a while. I'll contact him and see if we can get this work finished.

**Comment by jsbattig** [comment]
Development will continue with another developer.
New test files may be created.
